name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Force Push para o repositório pessoal
        run: |
          # Configura quem está fazendo o push
          git config --global user.name 'jvbenetti'
          git config --global user-email 'filipimjoa@gmail.com'
          
          # Adiciona o seu repo pessoal como um alvo usando o Token para autenticar
          # IMPORTANTE: Mude o nome do Secret se você renomeou no passo acima
          git remote add target https://${{ secrets.TOKEN_GITHUB }}@github.com/jvbenetti/sensor-view.git
          
          # Força o envio de tudo da main para a main do seu repo
          git push target main --force