name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Force Push para o repositório pessoal
        run: |
          # Configurações do Git (CORRIGIDO: user.name e user.email)
          git config --global user.name 'jvbenetti'
          git config --global user.email 'filipimjoa@gmail.com'
          
          # Remove o target caso ele já exista de uma execução falha anterior
          git remote remove target || true
          
          # Adiciona o seu repo pessoal usando o Token
          git remote add target https://${{ secrets.TOKEN_GITHUB }}@github.com/jvbenetti/sensor-view.git
          
          # Força o envio da branch main
          git push target main --force